server:
  port: 9001
spring:
  application:
    name: user
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8848
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: user-sentinel
            groupId: DEFAULT_GROUP
            data_type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true

logging:
  level:
    com.chippy: debug