server:
  port: 9004
spring:
  application:
    name: marketing
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      datasource:
        dsl:
          nacos:
            server-addr: localhost:8848
            dataId: marketing
            groupId: DEFAULT_GROUP
            data_type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true

logging:
  level:
    com.chippy: debug